# Generated by Django 4.2.7 on 2023-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('0', 'ToDo'), ('1', 'In Progress'), ('2', 'On Hold'), ('3', 'Done')], default='0', max_length=1),
        ),
    ]
