# Generated by Django 4.2.7 on 2023-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_goal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleddate',
            old_name='scheduled_time',
            new_name='end_time',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleddate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleddate',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='scheduleddate',
            name='start_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'ToDo'), ('1', 'In Progress'), ('2', 'On Hold'), ('3', 'Done')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleddate',
            unique_together={('date', 'start_time', 'end_time')},
        ),
    ]
