# Generated by Django 4.2.7 on 2023-11-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_scheduled_time_scheduleddate_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dates', to='tasks.task')),
            ],
            options={
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='scheduleddate',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduledDate',
        ),
    ]
