# Generated by Django 4.2.7 on 2023-11-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_scheduledtask_task_alter_scheduledtask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
