# Generated by Django 4.2.7 on 2023-11-21 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_alter_goal_title_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtask',
            unique_together={('date', 'start_time', 'end_time', 'user')},
        ),
    ]
